#!/bin/sh

cd ./detonationNSFoam_mixtureAverage
cd ./dynamicMesh2D/dynamicMesh
wmake
cd ../dynamicFvMesh
wmake
cd ../..
cd ./DLB/src/thermophysicalModels/chemistryModel
wmake
cd ../../../..
cd ./moleFractions
wmake
cd ..
cd ./laminarTransport
wmake
cd ..
cd ./fitTransport
wmake
cd ..
cd ./fluxSchemes
wmake
cd ..
wmake
cd ..

cd ./detonationNSFoam_Sutherland
cd ./dynamicMesh2D/dynamicMesh
wmake
cd ../dynamicFvMesh
wmake
cd ../..
cd ./DLB/src/thermophysicalModels/chemistryModel
wmake
cd ../../../..
cd ./fluxSchemes
wmake
cd ..
wmake
cd ..

cd ./detonationEulerFoam
cd ./dynamicMesh2D/dynamicMesh
wmake
cd ../dynamicFvMesh
wmake
cd ../..
cd ./DLB/src/thermophysicalModels/chemistryModel
wmake
cd ../../../..
cd ./fluxSchemes
wmake
cd ..
wmake
#------------------------------------------------------------------------------
